apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: MCPRoute
metadata:
  name: omnibus-mcp-route
  namespace: default
spec:
  parentRefs:
    - name: omnibus-ai-gateway
  path: /mcp
  backendRefs:
    - name: adminservice
      port: 8081
      path: /mcp/admin/sse
    - name: bookingservice
      port: 8083
      path: /mcp/booking/sse
    - name: inventoryservice
      port: 8084
      path: /mcp/inventory/sse