apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: omnibus-http-routes
  namespace: default
spec:
  parentRefs:
    - name: omnibus-gateway
      namespace: default
  rules:
    # 1. Admin Microservice
    - matches:
        - path:
            type: PathPrefix
            value: /adminservice/
      backendRefs:
        - name: adminservice
          port: 8081

    # 2. Booking Microservice
    - matches:
        - path:
            type: PathPrefix
            value: /bookingservice/
      backendRefs:
        - name: bookingservice
          port: 8083

    # 3. Inventory Microservice
    - matches:
        - path:
            type: PathPrefix
            value: /inventoryservice/
      backendRefs:
        - name: inventoryservice
          port: 8084

    # 4. Payment Microservice
    - matches:
        - path:
            type: PathPrefix
            value: /paymentservice/
      backendRefs:
        - name: paymentservice
          port: 8085

    # 5. Keycloak Application Realm & Theme Resources
    # Exclusively exposes the 'bus-reservation' realm (Discovery, JWKS, PKCE Token, Login).
    # Master realm and /admin console remain 100% blocked from the edge for security.
    - matches:
        - path:
            type: PathPrefix
            value: /realms/bus-reservation/
        - path:
            type: PathPrefix
            value: /resources/
      backendRefs:
        - name: keycloak
          port: 8080

    # 6. Default Frontend SPA
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: frontend
          port: 80
