# Import Shared Centralized Properties from common-security
spring.config.import=classpath:common-application.properties

# Service Identity & Port
spring.application.name=inventoryservice
server.port=8084

# H2 Database
spring.datasource.url=jdbc:h2:mem:inventorydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Spring AI Model Context Protocol (MCP) Server
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.name=omnibus-inventory-mcp
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.transport=sse
spring.ai.mcp.server.sse.path=/mcp/inventory/message
spring.ai.mcp.server.sse.sse-path=/mcp/inventory/sse