server.port=8084
spring.application.name=bookingservice

spring.profiles.active=dev
spring.config.import=configserver:http://localhost:8888/config

resilience4j.retry.configs.default.retry-exceptions[0]=org.springframework.web.server.ResponseStatusException

resilience4j.circuitbreaker.instances.seatsAvailabilityCB.base-config=default
resilience4j.retry.instances.seats-availability-retry.base-config=default