spring.application.name=service-registry
server.address=0.0.0.0
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false

spring.profiles.active=native
spring.cloud.config.server.prefix=/config
spring.cloud.config.server.native.search-locations=classpath:/config,classpath:/config/{application}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.lease-expiration-duration-in-seconds=2
eureka.instance.lease-renewal-interval-in-seconds=1