server.application.name=authserver
server.port=9000

spring.datasource.url=jdbc:postgresql://:5432/defaultdb
spring.datasource.username=
spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=false
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=1

eureka.client.service-url.default-zone=http://localhost:8761/eureka
eureka.instance.lease-renewal-internal-in-seconds=1
eureka.instance.lease-expiration-duration-in-seconds=2

ribbon.eureka.enabled=false

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

myapp.client.id=gateway-client-id
myapp.client.secret=secret
myapp.client.redirectUri=http://localhost:4200/callback