spring.application.name=myjpa
server.port=8080

spring.datasource.url=jdbc:postgresql://dheerupostgres-springsql.a.aivencloud.com:18567/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_xAnvRyczjemp4Vz2FJA

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=1

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true